In [12]:
import numpy as np
import pandas as pd
from tabulate import tabulate
from pandas import Series
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt
from IPython.display import display
import re


col_list = ["name", "price","fdName","leibie","cat","url"]
product = pd.read_csv("E://unique_product06.csv", usecols=col_list, )#.dropna(thresh=2)#.head()

print(product.shape)

(264363, 6)

In [13]:
# df = product['leibie'].str.split(',', expand=True)
# product['tab']= df[0]
# product['cat']= df[1]
# print(DataDF.UnitPrice.fillna(method='ffill')) # 前向后填充
# print(DataDF.UnitPrice.fillna(method='bfill')) # 后向前填充


new_df = product[['name', 'price','fdName', 'leibie','cat']]

display(new_df.head(50))
print(new_df.shape)

,name,price,fdName,leibie,cat
0,little ones baby wipes unscented,2.20,Beachlands,browse,Baby care
1,essentials baby wipes fragrance free,1.80,Beachlands,browse,Baby care
2,huggies baby wipes unscented,13.00,Beachlands,browse,Baby care
3,huggies baby wipes unscented,3.00,Beachlands,browse,Baby care
4,huggies essentials walker nappies unisex 13-18...,15.00,Beachlands,browse,Baby care
5,silk baby wipes fragrance free,2.39,Beachlands,browse,Baby care
6,only organic stage 2 baby food banana blueberr...,1.99,Beachlands,browse,Baby care
7,only organic stage 3 baby food banana berries ...,1.99,Beachlands,browse,Baby care
8,huggies ultra dry walker boy nappies 13-18kg s...,20.00,Beachlands,browse,Baby care
9,huggies ultra dry nappy pants junior boy size 6,20.00,Beachlands,browse,Baby care
10,huggies essentials toddler nappies unisex 10-1...,15.00,Beachlands,browse,Baby care
11,"only organic stage 3 baby food banana, raspber...",1.99,Beachlands,browse,Baby care
12,friends nappy bags odourised,1.99,Beachlands,browse,Baby care
13,huggies ultra dry nappy pants walker boy size 5,20.00,Beachlands,browse,Baby care
14,vanish napisan oxi action laundry soaker fabri...,8.00,Beachlands,browse,Baby care
15,huggies baby wipes aloe & cucumber,3.00,Beachlands,browse,Baby care
16,"only organic stage 2 baby food pear, apple & b...",1.99,Beachlands,browse,Baby care
17,little bellies round abouts baby snacks perfec...,1.90,Beachlands,browse,Baby care
18,essentials baby wipes scented,1.80,Beachlands,browse,Baby care
19,huggies baby wipes coconut,3.00,Beachlands,browse,Baby care
20,huggies ultra dry infant 4-8kg size 2,20.00,Beachlands,browse,Baby care
21,huggies baby wipes cucumber & aloe,13.00,Beachlands,browse,Baby care
22,karicare stage 2 follow on from 6 months formula,18.00,Beachlands,browse,Baby care
23,huggies ultra dry toddler girl nappies 10-15kg...,20.00,Beachlands,browse,Baby care
24,countdown smiling tums baby food beef & vegeta...,1.75,Beachlands,browse,Baby care
25,raffertys garden plant protein baby food brown...,2.00,Beachlands,browse,Baby care
26,huggies ultra dry toddler girl nappies 10-15kg...,34.00,Beachlands,browse,Baby care
27,s26 original toddler from 1 year formula stage 3,21.50,Beachlands,browse,Baby care
28,treasures care nappy pants size 4 toddler 10-1...,15.00,Beachlands,browse,Baby care
29,treasures care walker size 5 nappies 13-18kg,15.00,Beachlands,browse,Baby care
30,"johnsons baby powder pure cornstarch, aloe & v...",5.29,Beachlands,browse,Baby care
31,watties organic baby food apple pumkin & kumara,2.09,Beachlands,browse,Baby care
32,huggies ultra dry walker boy nappies 13-18kg s...,34.00,Beachlands,browse,Baby care
33,natureland baby food chocolate custard,1.80,Beachlands,browse,Baby care
34,huggies ultra dry toddler boy nappies 10-15kg ...,34.00,Beachlands,browse,Baby care
35,ecostore baby shampoo chamomile & lavender,6.99,Beachlands,browse,Baby care
36,watties organic baby food crmy van apple rice ...,2.09,Beachlands,browse,Baby care
37,ecostore baby bath sleepytime,6.99,Beachlands,browse,Baby care
38,watties organic stage 1 baby food apple medley,2.09,Beachlands,browse,Baby care
39,little quacker organic toddler biscuits banana...,2.50,Beachlands,browse,Baby care
40,johnsons baby shampoo original,4.20,Beachlands,browse,Baby care
41,"raffertys garden protein baby food beef, sett ...",2.00,Beachlands,browse,Baby care
42,heinz nurture starter from birth infant formula 1,17.50,Beachlands,browse,Baby care
43,heinz nurture follow on from 6 months formula ...,17.50,Beachlands,browse,Baby care
44,s26 gold newborn starter from birth formula st...,26.00,Beachlands,browse,Baby care
45,earth smart baby wipes all natural,4.00,Beachlands,browse,Baby care
46,little genie baby wipes biodegradable frag free,5.49,Beachlands,browse,Baby care
47,natureland baby food kumara sweetcorn baby rice,1.80,Beachlands,browse,Baby care
48,"watties stage 2 baby food pasta, vegetables & ...",1.80,Beachlands,browse,Baby care
49,"countdown smiling tums baby food sweet potato,...",1.75,Beachlands,browse,Baby care

(264363, 5)

In [15]:
test_df = product[['name']]
test_df.drop_duplicates()

                                                     name
0                        little ones baby wipes unscented
1                    essentials baby wipes fragrance free
2                            huggies baby wipes unscented
4       huggies essentials walker nappies unisex 13-18...
5                          silk baby wipes fragrance free
...                                                   ...
263211                                daim chocolate bar
263440                   romanos supreme pizza minis 450g
263735             san remo gluten free pasta fettuccine
264066  watties wok creations stir fry sauce malaysian...
264069               ceres organics lentils organic brown

[13492 rows x 1 columns]

In [17]:
new_df = pd.read_csv("E:/unique_product06.csv",usecols=col_list, skipinitialspace=True, skip_blank_lines=True)
display(new_df)

,name,price,fdName,leibie,cat,url
0,little ones baby wipes unscented,2.20,Beachlands,browse,Baby care,https://shop.countdown.co.nz/shop/productdetai...
1,essentials baby wipes fragrance free,1.80,Beachlands,browse,Baby care,https://shop.countdown.co.nz/shop/productdetai...
2,huggies baby wipes unscented,13.00,Beachlands,browse,Baby care,https://shop.countdown.co.nz/shop/productdetai...
3,huggies baby wipes unscented,3.00,Beachlands,browse,Baby care,https://shop.countdown.co.nz/shop/productdetai...
4,huggies essentials walker nappies unisex 13-18...,15.00,Beachlands,browse,Baby care,https://shop.countdown.co.nz/shop/productdetai...
...,...,...,...,...,...,...
264358,purina cat chow cat biscuits complete,40.00,Papakura,specials,Pet care,https://shop.countdown.co.nz/shop/productdetai...
264359,purina beneful dry dog food simple goodness beef,16.00,Papakura,specials,Pet care,https://shop.countdown.co.nz/shop/productdetai...
264360,purina one dog food beef grain free,21.00,Papakura,specials,Pet care,https://shop.countdown.co.nz/shop/productdetai...
264361,harringtons adult cat food rich in salmon with...,15.00,Papakura,specials,Pet care,https://shop.countdown.co.nz/shop/productdetai...
264362,omega plus wet cat food salmon and caviar,1.89,Papakura,specials,Pet care,https://shop.countdown.co.nz/shop/productdetai...

In [18]:
# 检查缺失值
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264363 entries, 0 to 264362
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   name    264363 non-null  object
 1   price   264363 non-null  float64
 2   fdName  264363 non-null  object
 3   leibie  264363 non-null  object
 4   cat     264363 non-null  object
 5   url     264363 non-null  object
dtypes: float64(1), object(5)
memory usage: 12.1+ MB

In [20]:
#分店类别价格均值
new_df.groupby(['fdName','leibie','cat'])['price'].agg(np.mean)

fdName      leibie    cat
Beachlands  browse    Baby care               9.484148
                      Bakery                  4.809553
                      Baking & cooking        3.937130
                      Biscuits & crackers     3.345063
                      Breakfast foods         6.491320
                                               ...
Papakura    specials  Health & wellness      14.428645
                      Liquor - wine          15.706000
                      Meal ingredients        3.809868
                      Personal care           9.696351
                      Pet care               12.176000
Name: price, Length: 883, dtype: float64

In [19]:
#分店价格均值
new_df.groupby('fdName')['price'].agg(np.mean)

fdName
Beachlands           7.067133
Birkenhead           7.037132
Blockhouse Bay       7.181457
Botany Downs         7.243830
Favona               7.232030
Glen Eden            7.113584
Glenfield            7.317625
Greenlane            7.237669
Grey Lynn            6.795986
Hauraki              7.240316
Helensville          7.139497
Helensville Rural    7.041535
Henderson            7.119728
Henderson Heights    7.118440
Henderson Valley     7.117302
Highland Park        7.190810
Howick               7.233757
Mairangi Bay         6.750000
Mangere              6.764584
Mangere East         7.242101
Manukau CBD          7.242300
Manukau Heads        7.051046
Manurewa             6.762940
Milford              8.534968
Papakura             6.926305
Name: price, dtype: float64

In [21]:
#分店价格方差
new_df.groupby('fdName')['price'].agg(np.var)

fdName
Beachlands           47.351053
Birkenhead           46.203027
Blockhouse Bay       48.029330
Botany Downs         60.986333
Favona               60.328931
Glen Eden            47.457487
Glenfield            66.637189
Greenlane            60.770640
Grey Lynn            41.886849
Hauraki              61.489419
Helensville          49.904849
Helensville Rural    47.552532
Henderson            47.598607
Henderson Heights    47.483246
Henderson Valley     47.442779
Highland Park        61.233744
Howick               60.743564
Mairangi Bay          2.250000
Mangere              44.111542
Mangere East         60.946963
Manukau CBD          60.945466
Manukau Heads        47.740638
Manurewa             41.974522
Milford              61.424653
Papakura             44.654785
Name: price, dtype: float64

In [22]:
#new_df['name'].value_counts().head(50)
#各店商品数量
new_df.groupby('fdName')['name'].value_counts().head(50)

fdName      name
Beachlands  glad plastic wrap cling                                       6
            coca cola soft drink diet coke                                5
            coca cola soft drink no sugar                                 5
            countdown water still spring                                  5
            l & p soft drink lemon & paeroa                               5
            sistema klip it container rectangle                           5
            sprite soft drink no sugar                                    5
            bundaberg ginger beer                                         4
            heineken lager                                                4
            mainland cheese block colby                                   4
            mainland cheese block edam                                    4
            mainland cheese block tasty                                   4
            moccona instant coffee classic medium                         4
            nestle milo drinking chocolate                                4
            sanitarium up & go breakfast drink choc ice                   4
            sanitarium up & go breakfast drink vanilla ice                4
            sistema ultra container tritan                                4
            sprite soft drink lemonade                                    4
            active rapid dishwasher tablets lime & baking soda            3
            alfa one rice bran oil                                        3
            beehive streaky bacon                                         3
            bell tea bags                                                 3
            berocca performance effervescent orange                       3
            bundaberg lemon, lime & bitters                               3
            campbells real stock beef stock liquid                        3
            campbells real stock chicken stock liquid                     3
            chelsea white sugar                                           3
            choysa tea bags classic                                       3
            coca cola soft drink                                          3
            colgate cavity protection toothpaste great regular flavour    3
            colgate plax mouth rinse fresh mint                           3
            colgate total toothpaste                                      3
            colgate triple action toothpaste original mint                3
            countdown cheese block colby                                  3
            countdown cheese block edam                                   3
            countdown cheese block tasty                                  3
            countdown middle bacon                                        3
            countdown milk lite                                           3
            countdown milk standard                                       3
            countdown milk trim                                           3
            countdown white sugar                                         3
            db export gold beer                                           3
            dilmah tea bags tagless                                       3
            earthwise laundry liquid fragrance free                       3
            earthwise laundry liquid orange & eucalyptus                  3
            fab laundry powder frangipani front & top                     3
            fanta soft drink orange                                       3
            friskies dry cat food surfin & turfin favourites              3
            huggies ultra dry crawler boy nappies 6-11kg size 3           3
            huggies ultra dry toddler boy nappies 10-15kg size 4          3
Name: name, dtype: int64

In [23]:
#各类别数量
new_df.groupby(['fdName','leibie'])['cat'].value_counts().head(50)

fdName      leibie    cat
Beachlands  browse    Baking & cooking               575
                      Canned & prepared foods        575
                      Frozen foods                   575
                      Pet care                       573
                      Liquor - wine                  572
                      Cleaning & homecare            571
                      Drinks - hot & cold            563
                      Chocolate, sweets & snacks     561
                      Personal care                  553
                      Meal ingredients               549
                      Breakfast foods                515
                      Deli & chilled foods           491
                      Baby care                      458
                      Bakery                         447
                      Biscuits & crackers            395
                      Home & kitchenware             392
                      Health & wellness              282
                      Fruit & vegetables             278
                      Clothing & manchester          241
                      Meat                           218
                      Liquor - beer & cider          209
                      Toys & party needs             181
                      Office & entertainment         162
                      Seafood                         70
                      Pharmacy                         1
            specials  Personal care                  273
                      Deli & chilled foods           231
                      Drinks - hot & cold            203
                      Meal ingredients               190
                      Liquor - wine                  161
                      Chocolate, sweets & snacks     154
                      Health & wellness              150
                      Baking & cooking                94
                      Cleaning & homecare             74
                      Frozen foods                    36
                      Pet care                        12
                      Canned & prepared foods          6
                      Bakery                           1
                      Clothing & manchester            1
Birkenhead  browse    Baking & cooking               576
                      Frozen foods                   575
                      Liquor - wine                  575
                      Pet care                       574
                      Cleaning & homecare            571
                      Canned & prepared foods        569
                      Chocolate, sweets & snacks     562
                      Drinks - hot & cold            560
                      Personal care                  556
                      Meal ingredients               549
                      Breakfast foods                518
Name: cat, dtype: int64

In [24]:
# 各項統計值
new_df.groupby('fdName')['price'].describe()

,count,mean,std,min,25%,50%,75%,max
fdName,,,,,,,,
Beachlands,11593.0,7.067133,6.881210,0.50,3.00,4.99,8.500,135.0
Birkenhead,11175.0,7.037132,6.797281,0.50,3.00,4.99,8.500,118.0
Blockhouse Bay,11565.0,7.181457,6.930320,0.50,3.00,5.00,8.990,118.0
Botany Downs,12144.0,7.243830,7.809375,0.50,3.00,5.00,8.990,300.0
Favona,12150.0,7.232030,7.767170,0.50,3.00,5.00,8.990,300.0
Glen Eden,11600.0,7.113584,6.888939,0.50,3.00,4.99,8.790,118.0
Glenfield,11878.0,7.317625,8.163160,0.50,3.00,5.00,8.990,300.0
Greenlane,12155.0,7.237669,7.795553,0.50,3.00,5.00,8.990,300.0
Grey Lynn,10225.0,6.795986,6.472005,0.50,3.00,4.80,8.000,118.0
Hauraki,11755.0,7.240316,7.841519,0.50,3.00,5.00,8.990,300.0
Helensville,11718.0,7.139497,7.064336,0.50,3.00,4.99,8.500,118.0
Helensville Rural,8764.0,7.041535,6.895834,0.50,2.99,4.50,8.990,100.0
Henderson,11601.0,7.119728,6.899174,0.50,3.00,4.99,8.790,118.0
Henderson Heights,11599.0,7.118440,6.890809,0.50,3.00,4.99,8.790,118.0
Henderson Valley,11599.0,7.117302,6.887872,0.50,3.00,4.99,8.790,118.0
Highland Park,11959.0,7.190810,7.825199,0.50,3.00,5.00,8.545,300.0
Howick,12144.0,7.233757,7.793816,0.50,3.00,5.00,8.990,300.0
Mairangi Bay,4.0,6.750000,1.500000,6.00,6.00,6.00,6.750,9.0
Mangere,10968.0,6.764584,6.641652,0.50,3.00,4.70,8.000,118.0
Mangere East,12154.0,7.242101,7.806854,0.50,3.00,5.00,8.990,300.0
Manukau CBD,12154.0,7.242300,7.806758,0.50,3.00,5.00,8.990,300.0
Manukau Heads,8774.0,7.051046,6.909460,0.50,2.99,4.50,9.000,100.0
Manurewa,10915.0,6.762940,6.478775,0.50,3.00,4.80,8.000,118.0
Milford,2466.0,8.534968,7.837388,0.95,3.20,6.00,11.000,70.0
Papakura,11304.0,6.926305,6.682424,0.50,3.00,4.99,8.490,118.0

In [25]:
# 各項統計值
new_df.groupby(['fdName','leibie','cat'])['price'].describe()

                                         count       mean        std   min  \
fdName     leibie   cat
Beachlands browse   Baby care            458.0   9.484148   8.463123  1.00
                    Bakery               447.0   4.809553   4.052793  0.70
                    Baking & cooking     575.0   3.937130   2.348601  0.90
                    Biscuits & crackers  395.0   3.345063   1.632997  1.00
                    Breakfast foods      515.0   6.491320   3.506147  1.50
...                                        ...        ...        ...   ...
Papakura   specials Health & wellness    155.0  14.428645   9.046964  1.90
                    Liquor - wine        100.0  15.706000   6.281315  9.00
                    Meal ingredients     152.0   3.809868   1.904281  0.95
                    Personal care        222.0   9.696351   7.188344  2.00
                    Pet care              10.0  12.176000  12.002105  1.89

                                           25%   50%    75%    max
fdName     leibie   cat
Beachlands browse   Baby care             2.09   7.0  13.00  45.99
                    Bakery                3.40   4.0   5.00  35.00
                    Baking & cooking      2.00   3.3   4.90  16.00
                    Biscuits & crackers   2.25   3.0   4.00  12.99
                    Breakfast foods       4.00   5.9   7.50  31.90
...                                        ...   ...    ...    ...
Papakura   specials Health & wellness     8.70  13.0  18.00  49.99
                    Liquor - wine        10.00  13.9  20.00  34.00
                    Meal ingredients      2.50   3.5   4.50  11.99
                    Personal care         4.00   8.0  13.00  40.00
                    Pet care              2.74   9.5  15.75  40.00

[883 rows x 8 columns]

In [26]:
#分店商品均值
df_price_mean = new_df.groupby(['fdName','leibie','cat'])['price'].mean().sort_values(ascending=False).to_frame().reset_index()

display(df_price_mean)

                fdName    leibie                  cat      price
0            Greenlane  specials  Home & kitchenware   35.000000
1               Howick  specials  Home & kitchenware   35.000000
2          Manukau CBD  specials       Liquor - wine   24.542723
3         Mangere East  specials       Liquor - wine   24.530841
4         Botany Downs  specials       Liquor - wine   24.530841
..                 ...       ...                  ...        ...
878           Manurewa  specials              Bakery    1.900000
879     Blockhouse Bay  specials            Pet care    1.890000
880  Helensville Rural  specials            Pet care    1.890000
881         Beachlands  specials              Bakery    1.800000
882        Helensville  specials              Bakery    1.800000

[883 rows x 4 columns]

In [27]:
df_price_mean = new_df.groupby(['fdName','cat'])['price'].mean().sort_values(ascending=True).to_frame().reset_index()
display(df_price_mean)

                fdName                  cat      price
0           Beachlands              Bakery    1.800000
1          Helensville              Bakery    1.800000
2       Blockhouse Bay            Pet care    1.890000
3    Helensville Rural            Pet care    1.890000
4             Manurewa              Bakery    1.900000
..                 ...                  ...        ...
878       Botany Downs       Liquor - wine   24.530841
879       Mangere East       Liquor - wine   24.530841
880        Manukau CBD       Liquor - wine   24.542723
881             Howick  Home & kitchenware   35.000000
882          Greenlane  Home & kitchenware   35.000000

[883 rows x 3 columns]

In [28]:
df_item_count = new_df.groupby('fdName')['name'].count().sort_values(ascending=False).to_frame().reset_index()
display(df_item_count)

               fdName   name
0           Greenlane  12155
1         Manukau CBD  12154
2        Mangere East  12154
3              Favona  12150
4        Botany Downs  12144
5              Howick  12144
6       Highland Park  11959
7           Glenfield  11878
8             Hauraki  11755
9         Helensville  11718
10          Henderson  11601
11          Glen Eden  11600
12   Henderson Valley  11599
13  Henderson Heights  11599
14         Beachlands  11593
15     Blockhouse Bay  11565
16           Papakura  11304
17         Birkenhead  11175
18            Mangere  10968
19           Manurewa  10915
20          Grey Lynn  10225
21      Manukau Heads   8774
22  Helensville Rural   8764
23            Milford   2466
24       Mairangi Bay      4

In [30]:
#词频
new_df.name.str.split(expand=True).stack().value_counts()

&            37028
countdown    15798
food         15205
chicken      11079
chocolate    10720
             ...
85-90            1
3-4              1
maltexo          1
jp               1
tai-yo           1
Length: 7225, dtype: int64

In [31]:

1. 同一个商品有没有存在不同的类cat里

2. 每个cat中价格的区间（包括special和browse），看看有没有区分性（对，把special和browse算做两个不同商品 因为价格不一样）（你也可以看看每家店之间不同的商品是哪些）

3. 分析不同cat之间的词频有没有显著差异

SyntaxError: invalid syntax (<ipython-input-31-d59e9e878795>, line 1)

In [38]:
#每个cat中价格的区间
price_df = final_df.groupby(['cat','leibie'])['price'].describe()

In [40]:
price_df

                                       count       mean        std    min  \
cat                        leibie
Baby care                  browse    10877.0   9.983084   9.300853   1.00
                           specials     18.0   8.251667   6.893666   1.90
Bakery                     browse     9413.0   4.735659   3.948107   0.70
                           specials     14.0   4.500000   2.873486   1.80
Baking & cooking           browse    13232.0   3.909825   2.313786   0.90
                           specials   2128.0   4.972538   2.788937   1.50
Biscuits & crackers        browse     9087.0   3.367528   1.665255   1.00
                           specials     34.0   4.650000   1.344856   1.70
Breakfast foods            browse    11254.0   6.579213   3.812637   1.50
                           specials    128.0  12.807734   6.127046   3.00
Canned & prepared foods    browse    12982.0   2.801242   1.466002   0.70
                           specials    104.0   3.762404   2.639927   1.30
Chocolate, sweets & snacks browse    12891.0   3.582738   2.016502   0.70
                           specials   3481.0   3.580569   2.379561   0.50
Cleaning & homecare        browse    13122.0   6.724483   4.672657   0.90
                           specials   1933.0   9.683751   5.088879   2.00
Clothing & manchester      browse     5290.0   9.093053   5.027390   1.50
                           specials     45.0   9.000000   2.785922   5.50
Deli & chilled foods       browse    10373.0   5.652131   3.616386   1.00
                           specials   5037.0   6.414590   4.863928   1.50
Drinks - hot & cold        browse    12946.0   5.555785   4.161598   0.90
                           specials   5061.0   4.927576   3.306309   1.00
Frozen foods               browse    12064.0   6.663446   3.363918   1.50
                           specials    878.0   6.500103   2.373527   1.70
Fruit & vegetables         browse     6240.0   4.927944   3.057703   0.50
Health & wellness          browse     6819.0   7.646557   5.617581   1.00
                           specials   3677.0  13.914400   8.698940   1.00
Home & kitchenware         browse     8993.0  10.535648  11.818527   1.00
                           specials     40.0  12.542000  10.230096   1.50
Liquor - beer & cider      browse     5643.0  16.033468   9.890234   1.99
                           specials     96.0  15.548958   9.132233   3.00
Liquor - wine              browse    13200.0  14.782354   7.365293   4.00
                           specials   4062.0  21.790350  21.140464   4.00
Meal ingredients           browse    12646.0   3.414505   2.399935   0.60
                           specials   4458.0   4.057106   2.276835   0.95
Meat                       browse     4015.0  14.616892   8.054144   4.00
                           specials      2.0  16.500000   9.192388  10.00
Office & entertainment     browse     3685.0   8.376456  13.412054   0.70
                           specials      7.0   5.500000   1.258306   4.00
Personal care              browse    12759.0   5.746720   3.367719   0.90
                           specials   6569.0   9.904835   6.950783   1.50
Pet care                   browse    13176.0   7.611941   7.330709   1.00
                           specials    559.0  10.462952  11.522579   1.00
Pharmacy                   browse       22.0  10.000000   0.000000  10.00
                           specials      1.0  10.000000        NaN  10.00
Seafood                    browse     1497.0  11.403941   8.903543   1.50
Toys & party needs         browse     3797.0   5.029826   4.553580   0.59
                           specials      8.0   6.750000   1.388730   6.00

                                        25%    50%      75%     max
cat                        leibie
Baby care                  browse     2.090   7.00  13.0000   45.99
                           specials   2.090   6.50  11.9975   20.00
Bakery                     browse     3.200   4.00   5.0000   35.00
                           specials   2.875   4.50   4.8750   13.50
Baking & cooking           browse     2.000   3.30   4.8000   16.00
                           specials   3.000   4.30   6.0000   20.00
Biscuits & crackers        browse     2.300   3.00   4.0000   14.99
                           specials   3.575   5.00   5.3750    7.30
Breakfast foods            browse     4.000   5.80   7.4900   31.90
                           specials   7.900  13.00  15.0000   25.50
Canned & prepared foods    browse     1.800   2.50   3.5000   17.90
                           specials   2.600   3.00   3.5000   17.90
Chocolate, sweets & snacks browse     2.490   3.29   4.4000   19.00
                           specials   2.350   3.00   4.0000   19.90
Cleaning & homecare        browse     3.890   5.00   8.0000   30.00
                           specials   6.000   8.00  12.0000   35.00
Clothing & manchester      browse     6.000   8.00  12.0000   29.99
                           specials   7.000   9.00  10.0000   25.00
Deli & chilled foods       browse     3.690   4.90   6.2000   29.90
                           specials   4.000   5.00   6.9900   65.00
Drinks - hot & cold        browse     3.000   4.30   6.9900   26.99
                           specials   2.800   4.00   6.5000   33.00
Frozen foods               browse     4.000   6.20   8.5000   30.00
                           specials   5.000   6.50   7.5000   20.00
Fruit & vegetables         browse     3.500   4.50   5.4900   36.00
Health & wellness          browse     3.990   5.89   9.0000   49.99
                           specials   8.000  13.00  18.0000   49.99
Home & kitchenware         browse     4.000   8.00  12.0000  118.00
                           specials   5.500   9.00  16.8750   35.00
Liquor - beer & cider      browse     8.000  14.00  22.0000   59.99
                           specials   6.500  16.00  22.0000   40.00
Liquor - wine              browse    10.000  13.99  17.9900   89.99
                           specials  12.000  17.00  25.0000  300.00
Meal ingredients           browse     2.000   3.00   3.9900   37.90
                           specials   2.500   3.69   5.0000   20.40
Meat                       browse     9.000  12.00  17.5000   68.00
                           specials  13.250  16.50  19.7500   23.00
Office & entertainment     browse     2.500   5.00   8.5000  100.00
                           specials   5.000   5.00   5.7500    8.00
Personal care              browse     3.500   5.00   7.0000   27.99
                           specials   4.400   8.00  13.5000   40.00
Pet care                   browse     2.500   5.00  11.0000   60.00
                           specials   1.990   6.00  15.0000   60.00
Pharmacy                   browse    10.000  10.00  10.0000   10.00
                           specials  10.000  10.00  10.0000   10.00
Seafood                    browse     4.200   9.00  17.0000   70.00
Toys & party needs         browse     2.500   3.50   6.0000   40.00
                           specials   6.000   6.00   6.7500    9.00

In [46]:
no_duplicates = final_df['name'].drop_duplicates()

In [47]:
no_duplicates.duplicated().sum().sum()

0

In [48]:
final_df.isna().sum()

name      0
price     0
fdName    0
leibie    0
cat       0
dtype: int64

In [41]:
#同一个商品有没有存在不同的类cat里
cats = final_df.groupby('name')['cat'].nunique().sort_values(ascending = False)
display(cats)

name
remedy organic kombucha peach              3
remedy kombucha apple crisp                3
amplify organic kombucha raspberry lime    3
ceres organics fritter mix                 3
simply squeezed orange juice               2
                                          ..
ob finest crackers cashew & rosemary       1
ob finest crackers black pepper wafers     1
ob finest crackers apricot & hazelnut      1
ob finest crackers 3 seed crisps           1
100% kiwi olive oil extra virgin           1
Name: cat, Length: 13492, dtype: int64

In [42]:
final_df.groupby('name')['cat'].unique()

name
100% kiwi olive oil extra virgin                            [Meal ingredients]
18 degrees south frozen blueberries                             [Frozen foods]
18 degrees south frozen mixed berries four fruit mix            [Frozen foods]
18 degrees south frozen mixed berries three berry mix           [Frozen foods]
180 degrees 4 seed oat crackers cumin                    [Biscuits & crackers]
                                                                 ...
zilch ice cream no added sugar vanilla                          [Frozen foods]
zovirax cold sore remedy cream                             [Health & wellness]
zovirax cold sore remedy pump                              [Health & wellness]
zuru pets alive toy boppi llama                           [Toys & party needs]
zuru xshot bunch of balloons water balloons               [Toys & party needs]
Name: cat, Length: 13492, dtype: object

In [43]:
final_df.groupby('name').get_group('remedy organic kombucha peach')

,name,price,fdName,leibie,cat
10437,remedy organic kombucha peach,3.0,Beachlands,specials,Deli & chilled foods
21752,remedy organic kombucha peach,3.0,Birkenhead,specials,Deli & chilled foods
33249,remedy organic kombucha peach,3.0,Blockhouse Bay,specials,Deli & chilled foods
45138,remedy organic kombucha peach,3.0,Botany Downs,specials,Deli & chilled foods
57286,remedy organic kombucha peach,3.0,Favona,specials,Deli & chilled foods
69112,remedy organic kombucha peach,3.0,Glen Eden,specials,Deli & chilled foods
80811,remedy organic kombucha peach,3.0,Glenfield,specials,Deli & chilled foods
92920,remedy organic kombucha peach,3.0,Greenlane,specials,Deli & chilled foods
100323,remedy organic kombucha peach,3.0,Grey Lynn,browse,Health & wellness
115025,remedy organic kombucha peach,3.0,Hauraki,specials,Deli & chilled foods
126804,remedy organic kombucha peach,3.0,Helensville,specials,Deli & chilled foods
147209,remedy organic kombucha peach,3.0,Henderson,specials,Deli & chilled foods
158810,remedy organic kombucha peach,3.0,Henderson Heights,specials,Deli & chilled foods
170407,remedy organic kombucha peach,3.0,Henderson Valley,specials,Deli & chilled foods
181920,remedy organic kombucha peach,3.0,Highland Park,specials,Deli & chilled foods
194279,remedy organic kombucha peach,3.0,Howick,specials,Deli & chilled foods
205741,remedy organic kombucha peach,3.0,Mangere,specials,Deli & chilled foods
217405,remedy organic kombucha peach,3.0,Mangere East,specials,Deli & chilled foods
229559,remedy organic kombucha peach,3.0,Manukau CBD,specials,Deli & chilled foods
249706,remedy organic kombucha peach,3.0,Manurewa,specials,Deli & chilled foods
250788,remedy organic kombucha peach,3.0,Milford,specials,Drinks - hot & cold
263382,remedy organic kombucha peach,3.0,Papakura,specials,Deli & chilled foods

In [44]:
cats

name
remedy organic kombucha peach              3
remedy kombucha apple crisp                3
amplify organic kombucha raspberry lime    3
ceres organics fritter mix                 3
simply squeezed orange juice               2
                                          ..
ob finest crackers cashew & rosemary       1
ob finest crackers black pepper wafers     1
ob finest crackers apricot & hazelnut      1
ob finest crackers 3 seed crisps           1
100% kiwi olive oil extra virgin           1
Name: cat, Length: 13492, dtype: int64

In [45]:
#cat词频
final_df.cat.str.split(expand=True).stack().value_counts().head(50)

&                146751
foods             52820
care              43958
-                 41008
Liquor            23001
Personal          19328
cold              18007
hot               18007
Drinks            18007
wine              17262
ingredients       17104
Meal              17104
Chocolate,        16372
snacks            16372
sweets            16372
chilled           15410
Deli              15410
Baking            15360
cooking           15360
homecare          15055
Cleaning          15055
Pet               13735
prepared          13086
Canned            13086
Frozen            12942
Breakfast         11382
Baby              10895
wellness          10496
Health            10496
Bakery             9427
Biscuits           9121
crackers           9121
kitchenware        9033
Home               9033
Fruit              6240
vegetables         6240
cider              5739
beer               5739
Clothing           5335
manchester         5335
Meat               4017
needs              3805
Toys               3805
party              3805
Office             3692
entertainment      3692
Seafood            1497
Pharmacy             23
dtype: int64